services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_DRIVER=${KC_DB_DRIVER}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
    ports:
      - "8080:8080"
    command: ["--verbose", "start-dev"]
    volumes:
      - ./dist/:/opt/keycloak/providers/
